# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments
# posts per page where you use pagination
paginate: 2

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Shawn's blog
tagline: Distributed OS, Algorithm, Network
author :
  name : Shawn Peng
  email : shawn.nc@gmail.com
  github : Shawn0720
#  twitter : username
#  feedburner : feedname

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://Shawn0720.github.io

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
atom_path : /atom.xml
rss_path : /rss.xml

# New markdown interpreter
markdown: redcarpet
